#!/bin/bash

set -euo pipefail

WORKSPACE=$(cd "$(dirname "${BASH_SOURCE[0]}")"/../.. && /bin/pwd -P)
PATH=$HOME/.local/bin:$PATH

pip install --user cpp-coveralls

# Build with coverage

mkdir "${WORKSPACE}/_build_coverage" && cd $_
CFLAGS="--coverage" CXXFLAGS="--coverage" LDFLAGS="--coverage" cmake .. -DUSE_THIRDPARTY_LIBRARIES=OFF "-DCMAKE_TOOLCHAIN_FILE=${VCPKG_INSTALLATION_ROOT}/scripts/buildsystems/vcpkg.cmake"
make -j$(nproc)
ctest -V -LE Benchmark

# Collect coverage data

export TRAVIS_BRANCH=${GITHUB_REF}
coveralls --root .. --build-root . --gcov-options '\-lp' -E ".*/3rdparty/.*" -E ".*/_.*" -E ".*/tests/.*" -E ".*/benchmarks/.*" -E "./CMake.*CompilerId.c"
