#!/bin/bash

set -euo pipefail

BUILDSYSTEM_ARG=${1:?}
OS_ARG=${2:?}

case "${OS_ARG}" in
    ubuntu*)
        packages=(locales)

        case "${BUILDSYSTEM_ARG}" in
            cmake)
                packages+=(python-pip python-wheel)
                ;;
        esac

        sudo apt-get remove -y --purge man-db # avoid time-consuming trigger
        sudo apt-get update
        sudo apt-get install -y "${packages[@]}"
        sudo locale-gen de_DE.UTF-8 # used by SerializerTest
        ;;
esac

case "${BUILDSYSTEM_ARG}" in
    cmake)
        "${VCPKG_INSTALLATION_ROOT}/vcpkg" install benchmark civetweb curl gtest zlib
        ;;
esac
