#!/bin/bash

set -euo pipefail

WORKSPACE=$(cd "$(dirname "${BASH_SOURCE[0]}")"/../.. && /bin/pwd -P)

# Build with internal dependencies

mkdir "${WORKSPACE}/_build_internal_deps" && cd $_
cmake .. -DUSE_THIRDPARTY_LIBRARIES=ON -DENABLE_WARNINGS_AS_ERRORS=ON -DENABLE_COMPRESSION=OFF -DENABLE_PUSH=OFF
make -j$(nproc)
ctest -V
mkdir -p deploy
make DESTDIR="${PWD}/deploy" install

# Build with external dependencies

mkdir "${WORKSPACE}/_build" && cd $_
cmake .. -DUSE_THIRDPARTY_LIBRARIES=OFF "-DCMAKE_TOOLCHAIN_FILE=${VCPKG_INSTALLATION_ROOT}/scripts/buildsystems/vcpkg.cmake"
make -j$(nproc)
ctest -V -LE Benchmark
mkdir -p deploy
make DESTDIR="${PWD}/deploy" install
