cc_library(
    name = "prometheus-cpp",
    srcs = ["lib/counter.cc",
            "lib/gauge.cc",
            "lib/exposer.cc",
            "lib/handler.cc",
            "lib/histogram.cc",
            "lib/registry.cc",
            "lib/text_serializer.cc",
            "lib/text_serializer.h",
            "lib/json_serializer.cc",
            "lib/json_serializer.h",
            "lib/serializer.h",
            "lib/protobuf_delimited_serializer.cc",
            "lib/protobuf_delimited_serializer.h",
            "lib/counter_builder.cc",
            "lib/gauge_builder.cc",
            "lib/histogram_builder.cc",
],
    hdrs = glob([
        "include/prometheus/*.h",
    ]),
    strip_include_prefix = "include",
    visibility = ["//visibility:public"],
    deps = ["@protobuf//:protobuf",
            "@prometheus_client_model//:prometheus_client_model",
            "@civetweb//:civetweb",
           ],
           linkstatic = 1,
           copts = ["-I."],
)
