name: Doxygen
on:
  push:
    branches:
      - master

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    name: Documentation
    runs-on: ubuntu-24.04
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Checkout source
        uses: actions/checkout@v6

      - name: Install doxygen
        run: |
          sudo apt-get remove -y --purge man-db # avoid time-consuming trigger
          sudo apt-get update
          sudo apt-get install -y doxygen graphviz

      - name: Generate doxygen
        run: doxygen
        working-directory: "${{ github.workspace }}/doc"

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./doc/html

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
