on:
  release:
    types: [created]

name: Handle Release

jobs:
  build:
    name: Upload Release Asset
    runs-on: ubuntu-slim
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          persist-credentials: false
          submodules: true

      - name: Create tarball including submodules
        shell: bash
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PREFIX: prometheus-cpp-with-submodules
        run: |
          git archive --prefix "${PREFIX}/" -o "${PREFIX}.tar" HEAD
          git submodule foreach --recursive "git archive --prefix=${PREFIX}/\$path/ --output=\$sha1.tar HEAD && tar --concatenate --file=$(pwd)/${PREFIX}.tar \$sha1.tar && rm \$sha1.tar"
          gzip "${PREFIX}.tar"
          gh release upload ${{ github.event.release.tag_name }} "${PREFIX}.tar.gz"
